### ISSUE TITLE
Create a docker image based on official PostgreSQL image

### ISSUE THREAD

**Issue by turicas** [bitnine-oss/agensgraph-docker#4]
Hello. First of all, thanks for this great sofware. <3

I've had some problems running the official Agensgraph Docker image (some non-default configurations needed to be made and other things, like non-standard PostgreSQL installation path etc.), so I decided to create a new image, based on [the official PostgreSQL Docker image](https://hub.docker.com/_/postgres).

It's based on Debian (I'm currently not supporting alpine by now) and has some good features, as:
- Lower footprint (114MB vs 620MB)
- Using a more up-to-date Agensgraph version (2.1.3 vs 2.1.1)
- Accepts all standard Docker postgres image environment variables

```shell
# docker image ls | grep agens
turicas/agensgraph     2.1.3               54c3b6865166        13 minutes ago      114MB
bitnine/agensgraph     v2.1.1              7e1892c80cb4        16 months ago       620MB
```

The code is available at https://github.com/turicas/agensgraph-docker and I'm willing to help make this an official Agensgraph image (we could also build for other versions and base images, like Alpine).

**Comment by emotionbug** [comment]
Hello. @turicas , First of all, I am very grateful.

can i clone commits on your repository for build new docker images?
If you agree, I will work immediately.

**Comment by emotionbug** [comment]
It has not been answered for a long time, so the issue is closed.

**Comment by turicas** [comment]
@emotionbug sorry, I didn't see the notifications. I didn't understand when you say "i clone commits on your repository" - should I do anything else than this PR? I'm willing to work on this so the PR can be accepted (I'm using this docker image and it's working pretty good).

**Comment by emotionbug** [comment]
@turicas 
Noooo.... I was impatient. I wanted PR, but there was no PR, so I copied the Repository and tried to apply it.
However, I thought it was not polite, so I closed the Issue and worked on it today.

Thank you for caring about this project. I hope you have a nice day.

**Comment by turicas** [comment]
There's no simple PR to do since I'm basing all my repository in the official postgres image, so I think if we go this way, the whole repository tree must be changed (we may add support for other versions as well and tag it). Again: I can work on this to make that repository the official one, I think it's more robust than the current one since it uses the official postgres Docker image as its base.

**Comment by emotionbug** [comment]
Yesterday, I worked on a postgres-based Docker. Is there any difference from your repository?
I don't know the difference except [debian: stretch-slim] based images.

**Comment by turicas** [comment]
> Yesterday, I worked on a postgres-based Docker. Is there any difference from your repository?
> I don't know the difference except [debian: stretch-slim] based images.

Yes. My repository is a fork from PostgreSQL's original docker image repository. I think this would be the best way to maintain the official AgensGraph repository/image: maintain a fork, pull the changes when they change anything on upstream postgres repo and always apply the patch (to use pre-compiled AgensGraph instead of installing PostgreSQL), as I did. I also suggest not storing the pre-compiled version here - it could be in AgensGraph's main repository as a release (the Docker image repository should download from there and this repository should have code only).

**Comment by emotionbug** [comment]
That's right. I agree with that opinion.
older than v2.1.3 used pre-compiled version. and, it can't able to test on compiling. and, don't know it is ok to running able.

so, switched like your code. and, it is good to use.
actually, refereed to your repository.

and, also before version required some command maintaining container. like ```docker run bitnine/agensgraph:v2.1.1 agens```. i think that is not good to use.

Crucially, I am very grateful to you, as I was inspired by your repository as a solution to this situation.
again, thanks to you.
