### ISSUE TITLE
\dG doesn't work

### ISSUE THREAD

**Issue by allentc** [bitnine-oss/agensgraph-docker#8]
Version tag: v2.1.3

As per the README.md "you can see the list of graphs created with the \dG command":

$ docker run --name agensgraph -e POSTGRES_PASSWORD=agensgraph -d bitnine/agensgraph:v2.1.3
$ docker exec -it agensgraph psql -U postgres
postgres=# \dG
Invalid command \dG. Try \? for help

There is no mention of \dG in \? help.

**Comment by emotionbug** [comment]
Oh sorry. Use agens instead of psql.

**Comment by allentc** [comment]
I see; using the 'agens' command works.  I didn't know the 'agens' command existed.  The README shows:

> bash-5.1# psql -u postgres

Thanks.
